# Uncomment this line to define a global platform for your project
platform :ios, '8.1'
# Uncomment this line if you're using Swift
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

workspace 'scuttle'

target 'scuttle' do
    
    pod 'SlackTextViewController'
    pod 'Alamofire', '~> 3.0'
    pod 'TwilioCommon', :podspec => 'https://media.twiliocdn.com/sdk/rtc/ios/common/v0.1/TwilioCommon.podspec'
    pod 'TwilioIPMessagingClient', :podspec => 'https://media.twiliocdn.com/sdk/rtc/ios/ip-messaging/v0.13/TwilioIPMessagingClient.podspec' 

end

target 'scuttleTests' do

end

target 'scuttleUITests' do

end

